services:
  svelte:
    container_name: tutorial-svelte-1
    build: ./web/cass-demo
    depends_on:
      cassandra-1:
        condition: service_healthy
      cassandra-2:
        condition: service_healthy
      cassandra-3:
        condition: service_healthy
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./web/cass-demo
          target: /app
  cassandra-1:
    container_name: tutorial-cassandra-1
    image: "cassandra:5.0.1"
    ports:
     - "9042"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
     - ./node-1/cassandra.yaml:/etc/cassandra/cassandra.yaml
     - ./node-1/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
     - ./node-1/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
     - ./node-1/data:/var/lib/cassandra
  cassandra-2:
    container_name: tutorial-cassandra-2
    image: "cassandra:5.0.1"
    ports:
     - "9042"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
     - ./node-2/cassandra.yaml:/etc/cassandra/cassandra.yaml
     - ./node-2/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
     - ./node-2/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
     - ./node-2/data:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: cassandra-1
  cassandra-3:
    container_name: tutorial-cassandra-3
    image: "cassandra:5.0.1"
    ports:
     - "9042"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
     - ./node-3/cassandra.yaml:/etc/cassandra/cassandra.yaml
     - ./node-3/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
     - ./node-3/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
     - ./node-3/data:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: cassandra-1
  cassandra-init-1:
    container_name: tutorial-cassandra-init-1
    image: "cassandra:5.0.1"
    depends_on:
     - cassandra-1
     - cassandra-2
     - cassandra-3
    restart: "no"
    entrypoint: ["/cassandra-init.sh"]
    volumes:
     - ./cassandra/cassandra-init.sh:/cassandra-init.sh
     - ./cassandra/cassandra-setup.cql:/cassandra-setup.cql
